### PR TITLE
Fix exception `[0] [] :J` in web version. Fix `['a] ['b 2] :J`.

### LINKED ISSUE #137: Web version unexpected exception for `[0] [] :J`
I tried running the asciitable examples in the web version and got an exception.

I have traced the cause to this:
```aya
[0] [0] :J
[] [] :J
[] [0] :J .# these work
[0] [] :J .# this doesn't
```
Exception:
```
An unhandled exception occurred. If this is a bug, please submit an issue to https://github.com/nick-paul/aya-lang/issues with the stacktrace below.
=== [ Stacktrace ] ===
java.lang.RuntimeException: (JavaScript) TypeError: Cannot read properties of undefined (reading 'data')

stack:
	[ 0 0 ] [ ] [ 0 ] 
TODO
Function call traceback:
```

Expected output (works in AyaIDE)
```
[ 0 0 ] [ ] [ 0 ] [ 0 ]
```

### PR DESCRIPTION
**Pull request by BlazingTwist**
Resolves #137

### CODE REVIEW

File: src/aya/obj/list/ListImpl.java [hunk 1]
```diff
@@ -89,10 +89,7 @@ public abstract class ListImpl {
 	
 	/** Return a list containing the unique elements of the original list */
 	public abstract ListImpl unique();
-	
-	/** Return true if the input object can be a valid member of the list */
-	public abstract boolean canInsert(Obj o);
```
Comment (BlazingTwist) [inline src/aya/obj/list/ListImpl.java:94]: `canInsert` already existed, but currently was never used.
Has been replaced with `canAccept` (which now is actually used)

File: src/aya/obj/list/ListImpl.java [hunk 2]
```diff
@@ -144,7 +151,7 @@ public abstract class ListImpl {
 
 	protected abstract byte type();
 
-	protected abstract boolean isa(byte type);
```
Comment (BlazingTwist) [inline src/aya/obj/list/ListImpl.java:147]: I'm not sure why this needs to be `public`, considering DoubleList inherits (transitively) from `ListImpl`

File: src/aya/obj/list/List.java [hunk 3]
```diff
@@ -663,24 +663,23 @@ public List permutations() {
...
-	
-	/** Set index i of the list to Obj o, throws an exception 
-	 * if the list is of lower type than o. (Ex: insert "hello" 
-	 * into a NumberList)
+
+	/**
+	 * Set index i of the list to Obj o.
+	 * Converts this list to one of higher type if needed.
 	 */
 	public void mutSetExact(int i, Obj o) {
```
Comment (BlazingTwist) [inline src/aya/obj/list/List.java:671]: The javadoc seems to have been wrong since 4e5933de081087fb953ebe506c61566eed92eb8a

**Comment by nick-paul** [comment]
Thanks, this PR also fixes several other operators which were crashing in the web version (all due to the same underlying issue). For instance, these would crash in the previous version but are fixed in the latest version.

```
[ 1 ] [ ] J
'a [0] .B
```

File: src/aya/obj/list/List.java (hunk 3 above)
Comment (nick-paul) [reply src/aya/obj/list/List.java:671]: Thanks for updating it
